// Builds the live staff app from its source (v1581).
//   node tools/build_index.js        (once: cd tools && npm install)
// src/index.src.html is the file to edit. The output index.html keeps all HTML and the small scripts inline, and every
// big inline script goes to js/admin-<n>-<hash>.js, comments and spacing removed by terser (no renaming, no rewriting).
// Why: a phone has to re-read and compile 4.5 MB of inline code on every open; a separate .js file is compiled once and
// kept by Chrome (code cache), and the hash in the name means a new version is never mixed with an old cached file.
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const { minify } = require(path.join(__dirname, 'node_modules', 'terser'));
const ROOT = path.join(__dirname, '..'), SRC = path.join(ROOT, 'src', 'index.src.html'), OUT = path.join(ROOT, 'index.html'), JS = path.join(ROOT, 'js');
const MIN_BYTES = 20000;
(async () => {
  const src = fs.readFileSync(SRC, 'utf8');
  if (!fs.existsSync(JS)) fs.mkdirSync(JS);
  const re = /<script([^>]*)>([\s\S]*?)<\/script>/g;
  let out = '', last = 0, n = 0; const files = [];
  for (let m; (m = re.exec(src)); ) {
    const attrs = m[1], code = m[2];
    const classic = !/\bsrc\s*=/.test(attrs) && (!/\btype\s*=/.test(attrs) || /type\s*=\s*["']text\/javascript["']/.test(attrs));
    if (!classic || Buffer.byteLength(code) < MIN_BYTES) continue;
    n++;
    const r = await minify(code, { compress: false, mangle: false, module: false, format: { comments: false, ascii_only: false } });
    if (r.error || typeof r.code !== 'string') throw new Error('terser failed on script ' + n + ': ' + r.error);
    const hash = crypto.createHash('sha1').update(r.code).digest('hex').slice(0, 10);
    const name = 'admin-' + n + '-' + hash + '.js';
    fs.writeFileSync(path.join(JS, name), r.code);
    files.push(name);
    out += src.slice(last, m.index) + '<script src="js/' + name + '"></script>';
    last = m.index + m[0].length;
    console.log('script', n, (Buffer.byteLength(code) / 1024).toFixed(0) + ' KB ->', name, (r.code.length / 1024).toFixed(0) + ' KB');
  }
  out += src.slice(last);
  out = out.replace(/<!DOCTYPE html>/i, d => d + '\n<!-- GENERATED by tools/build_index.js from src/index.src.html - edit that file, then run: node tools/build_index.js -->');
  fs.writeFileSync(OUT, out);
  for (const f of fs.readdirSync(JS)) if (/^admin-\d+-[0-9a-f]+\.js$/.test(f) && !files.includes(f)) fs.unlinkSync(path.join(JS, f));
  console.log('index.html', (Buffer.byteLength(out) / 1024).toFixed(0) + ' KB,', files.length, 'script files');
})().catch(e => { console.error('BUILD FAILED:', e.message); process.exit(1); });
